sudo: false
language: python
python:
    - 3.5
    - 3.6
install:
  - pip install -r contrib/requirements/requirements-travis.txt
cache:
  - pip: true
  - directories:
    - /tmp/electrum-ltc-build
script:
    - tox
after_success:
    - if [ "$TRAVIS_BRANCH" = "master" ]; then pip install pycurl requests && contrib/make_locale; fi
    - coveralls
jobs:
  include:
    - stage: windows build
      sudo: true
      python: 3.5
      install:
        - sudo dpkg --add-architecture i386
        - wget -nc https://dl.winehq.org/wine-builds/Release.key
        - sudo apt-key add Release.key
        - sudo apt-add-repository https://dl.winehq.org/wine-builds/ubuntu/
        - sudo apt-get update -qq
        - sudo apt-get install -qq winehq-stable dirmngr gnupg2 p7zip-full
      before_script: ls -lah /tmp/electrum-ltc-build
      script: ./contrib/build-wine/build.sh
      after_success: true
